# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: SciCat
email: max.novelli@ess.eu
description: Advance your data to advance your science
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://scicatproject.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_organization: SciCatProject
contact_email: scicat-info@lists.psi.ch
slack_channel: https://scicat.slack.com/archives/C08GYULHELQ
scicatcon_link: https://indico.ess.eu/event/3731/

version: 3.0.0
last_updated: 2025/03/06

backend_release:
  url: https://github.com/SciCatProject/scicat-backend-next
  version: Elastic Search, v4.4.0

frontend_release:
  url: https://github.com/SciCatProject/frontend
  version: Elastic Search, v4.4.0


facilities:
  - name: European Spallation Source
    image: /assets/images/facilities/ess_logo.png
    url: https://www.ess.eu
    contacts:
      - name: Max Novelli
        email: max.novelli@ess.eu
  - name: Paul Scherrer Institut
    image: /assets/images/facilities/psi_logo.svg
    url: https://www.psi.ch
    contacts:
      - name: Carlo Minotti
        email: scicat-help@lists.psi.ch
  - name: MAX IV
    image: /assets/images/facilities/maxiv_logo.png
    url: https://www.maxiv.lu.se/
    contacts:
      - name: Carla Takahashi
        email: carla.takahashi@maxiv.lu.se
  - name: Rosalind Franklin Institute
    image: /assets/images/facilities/rfi_logo.png
    url: https://www.rfi.ac.uk/
    contacts:
      - name: Laura Shemilt
        email: laura.shemilt@rfi.ac.uk
  - name: Heinz Maier-Leibnitz Zentrum
    image: /assets/images/facilities/mlz_logo.png
    url: https://mlz-garching.de/
    contacts:
      - name: Björn Pedersen
        email: bjoern.pedersen@frm2.tum.de
  - name: Advanced Light Source
    image: /assets/images/facilities/als_logo.png
    url: https://als.lbl.gov/
    contacts:
      - name: Dylan McReynolds
        email: dmcreynolds@lbl.gov
  - name: Deutsches Elektronen-Synchrotron
    image: /assets/images/facilities/desy_logo.png
    url: https://www.desy.de/
    contacts:
      - name: Regina Hinzmann
        email: regina.hinzmann@desy.de
  - name: Synchrotron SOLEIL
    image: /assets/images/facilities/soleil_logo.png
    url: https://www.synchrotron-soleil.fr
    contacts: 
      - name: Patrick Madela
        email: patrick.madela@synchrotron-soleil.fr
  - name: DAta from PHoton and Neutron Experiments
    image: /assets/images/facilities/daphne_logo.png
    url: https://www.daphne4nfdi.de
    contacts:
      - name: Regina Hinzmann
        email: regina.hinzmann@desy.de
      - name: Nicolas Hayen
        email: hayen@physik.uni-kiel.de
  - name: Helmholtz Zentrum Dresden Rossendorf
    image: /assets/images/facilities/hzdr_logo.png
    url: https://www.hzdr.de/
    contacts:
      - name: Oliver Knodel
        email: o.knodel@hzdr.de


team:
  leaders:
    - name: Max Novelli
      company: European Spallation Source (ESS)
      role: Project Leader
      url: https://github.com/nitrosx
    - name: Regina Hinzmann
      company: Deutsches Elektronen-Synchrotron (DESY)
      role: Documentation Leader
      url: https://github.com/rkweehinzmann
    - name: Björn Pedersen
      company: Heinz Maier-Leibnitz Zentrum (MLZ)
      role: PR and Issue Review Leader
      url: https://github.com/bpedersen2
    - name: Spencer Bliven
      company: Paul Scherrer Institut (PSI)
      role: Release Jobs Leader
      url: https://github.com/sbliven
    - name: Despina Adamopoulou 
      company: EMPA Material Science and Technology
      role: Website Leader
      url: https://github.com/despadam
    - name: Open Position
      company: Accepting candidates
      role: UI/UX Leader
      url: 


repositories:
  - name: frontend
  - name: scicat-backend-next
  - name: scicatlive
  - name: branding
  - name: scitacean
  - name: pyscicat


documentation:
  main:
    name: Get Started with SciCat Live
    description: To get started with a standalone installation of SciCat and to know more about how to add it to your infrastructure visit the SciCat Live repository.
    url: https://scicatproject.github.io/scicatlive/latest/
  others:
    - name: User Guides
      description: Experience SciCat as a user.
      url: https://scicatproject.github.io/documentation/
    - name: Ingestor
      description: Ingesting Data into SciCat.
      url: https://github.com/SciCatProject/documentation/tree/master/Ingestor
    - name: Developer
      description: The SciCat Data Catalogue Developer Guide.
      url: https://github.com/SciCatProject/documentation/tree/master/Development
    - name: Operator
      description: The SciCat Data Catalogue Operator Guide.
      url: https://github.com/SciCatProject/documentation/tree/master/Operator


# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
