# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: SciCat
email: max.novelli@ess.eu
description: Advance your data to advance your science
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://scicatproject.github.io" # the base hostname & protocol for your site, e.g. http://example.com

version: 2.2.1
last_updated: 2024/01/09

github_organization: SciCatProject


backend_release:
  url: https://github.com/SciCatProject/scicat-backend-next
  version: Elastic Search, v4.4.0

frontend_release:
  url: https://github.com/SciCatProject/frontend
  version: Elastic Search, v4.4.0


facilities:
  - image: /assets/images/ess_logo.png
    url: https://www.ess.eu
    name: European Spallation Source
    contactName: Junjie Quan
    contactEmail: 
  - image: /assets/images/psi_logo.png
    url: https://www.psi.ch
    name: Paul Scherrer Institut
    contactName: Carlo Minotti
    contactEmail:
  - image: /assets/images/maxiv_logo.png
    url: https://www.maxiv.lu.se/
    name: MAX IV
    contactName:
    contactEmail:
  - image: /assets/images/rfi_logo.png
    url: https://www.rfi.ac.uk/
    name: Rosalind Franklin Institute
    contactName:
    contactEmail:
  - image: /assets/images/mlz_blue_rgb.png
    url: https://mlz-garching.de/
    name: Heinz Maier-Leibnitz Zentrum
    contactName:
    contactEmail:
  - image: /assets/images/als_logo.png
    url: https://als.lbl.gov/
    name: Advanced Light Source
    contactName: Dylan McReynolds
    contactEmail:
  - image: /assets/images/desy_logo.png
    url: https://www.desy.de/
    name: Deutsches Elektronen-Synchrotron DESY
    contactName:
    contactEmail:
  - image: /assets/images/soleil_logo.png
    url: https://www.synchrotron-soleil.fr
    name: Synchrotron SOLEIL
    contactName: Javier Perez, Majid Ounsy, Patrick Madela
    contactEmail:
  - image: /assets/images/daphne_logo.png
    url: https://www.daphne4nfdi.de
    name: DAta from PHoton and Neutron Experiments
    contactName:
    contactEmail:


team:
  leaders:
    - name: Max Novelli
      company: European Spallation Source
      role: Project Leader
      url: https://github.com/nitrosx
    - name: Laura Shemilt
      company: Rosalind Franklin Institute
      role: Documentation Leader
      url: https://github.com/LAShemilt
    - name: Björn Pedersen
      company: Heinz Maier-Leibnitz Zentrum 
      role: PR and Issue Review Leader
      url: https://github.com/bpedersen2
    - name: Spencer Bliven
      company: PSI
      role: Release Jobs Leader
      url: https://github.com/sbliven
    - name: Igor Khokhriakov
      company: DESY
      role: Release Search UI Leader
      url: https://github.com/Ingvord


repositories:
  - name: frontend
  - name: scicat-backend-next
  - name: scicatlive
  - name: scitacean
  - name: pyscicat
  - name: scicat-sdk


documentation:
  main:
    name: Get Started with SciCat Live
    description: To get started with a standalone installation of SciCat and to know more about how to add it to your infrastructure visit the SciCat Live repository.
    url: https://scicatproject.github.io/scicatlive/latest/
  others:
    - name: User Guides
      description: Experience SciCat as a user.
      url: https://scicatproject.github.io/documentation/
    - name: Ingestor
      description: Ingesting Data into SciCat.
      url: https://github.com/SciCatProject/documentation/tree/master/Ingestor
    - name: Developer
      description: The SciCat Data Catalogue Developer Guide.
      url: https://github.com/SciCatProject/documentation/tree/master/Development
    - name: Operator
      description: The SciCat Data Catalogue Operator Guide.
      url: https://github.com/SciCatProject/documentation/tree/master/Operator


# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
